version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql      # Set the container name to 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis     # Set the container name to 'redis'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
volumes:
  mysql-data:
  redis-data:
